# Generated by Django 5.2.5 on 2025-10-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='promotable',
            field=models.BooleanField(default=False),
        ),
    ]
